version: "3.9"
services:
  eureka:
    build: /
    image: resource-service:${TAG}
    command: java -jar resource-service-0.0.1-SNAPSHOT.jar
    ports:
      - 8761:8761
    environment:
      spring.profiles.active: ${PROFILE}