version: "3.9"
services:
  resource-service:
    build: .
    image: resource-service:${TAG}
    command: java -jar resource-service-0.0.1-SNAPSHOT.jar
    environment:
      spring.profiles.active: ${PROFILE}
    networks:
      - ttc-tops
networks:
  ttc-tops:
    external: true
    name: ttc-tops
    driver: bridge


