spring:
  application:
    name: resource-service
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.web.reactive: DEBUG
